### ISSUE TITLE
Beschreibung / Ziele

### ISSUE THREAD

**Issue by meaku** [web-and-wine/orga#1]
> wie ich ja dem ein oder anderem schon persönlich erzählt hab, wollen wir die Web Community in Augsburg bei monatlichen Beertings zusammen bringen.
> Bisher war das Treffen noch einem elitären Kreis an der FH vorbehalten. Das wollen wir ändern und langsam mehr Leute ins Boot holen. 
> 
> Wir wollen uns in loser Form mit Web-Technologien beschäftigen. 
> Das heißt möglichst auf einem gemeinsamen Level ohne uns zu tief in die Eigenheiten bestimmter Frameworks zu verlieren. 
> 
> Im Frontend haben wir alle mit HTML / CSS / JavaScript zu tun. 
> Die Backends unterscheiden sich teilweise hinsichtlich der Sprachen, aber auch hier gibt es gemeinsame Nenner: HTTP(S) / WebSockets REST / API Konventionen 
> Und dann gibt es natürlich noch genug Meta-Themen die alle betreffen: TDD, CI/CD, Refactoring, Struktur, Server, Infrastruktur, Hosting
> 
> Sollten sich genug Leute finden, kann man auch gern mal Framework spezifische Themen anschneiden. 
> 
> Das ganze wird dann in Form von Vorträgen, Videos oder einfach kleinen Diskussionsgruppen verabreicht.

**Comment by meaku** [comment]
## Inhaltlich
- Web Community: Dev & Design
- nicht zu Framework spezifisch 
- neue Technologien
- Meta-Ebene 

## Format
- lockerer Austausch 
- Networking
- Lightning Talks (~10 Minuten)
- viel Diskussion
- 1x pro Monat 
- offen für alle (Limit ggf. bei meetup)
- wechselnde Locations 
- Hauptthema   / Treffen? 
- einmal pro Jahr -> Barcamp?! 

## Verpflegung
- Wein Wanderpokal mit Unterschrift der Gastgeber :wine_glass: 
- Wein (mindestens eine Flasche, des namens wegen)
- Bier 
- Essen

**Comment by Blacklist** [comment]
## Beschreibung

We have a dream that one day we will ... _räusper_ ... dass wir uns an einem festgelegten Tag zusammenfinden und uns bei einer oder mehreren Flaschen Wein über die neuesten Errungenschaften im Bereich Webdevelopment und -design austauschen.
Dabei wollen wir nicht zu frameworkspezifisch sein, sondern uns eher mit neuen Technologien beschäftigen, welche für den größtmöglichen Teil von uns relevant sind.
Neue Menschen, neue Gesichter, neue Meinungen und neue Eindrücke. Die Meta-Ebene ist uns extrem wichtig!

## Format
- offen für alle (Limit ggf. bei meetup)
- lockerer Austausch
- Networking
- Lightning Talks (~10 Minuten)
- viel Diskussion
- Treffen 1x pro Monat
- wechselndes Hauptthema pro Treffen
- wechselnde Locations (innerhalb Augsburg)
- Wanderwein-Pokal (Unterschrift aller bisherigen Gastgeber)

## Verpflegung
- Wein
- Bier
- nichtalkoholische Getränke
- Essen (z.B. Pizza je nach Saison)

**Comment by meaku** [comment]
Find ich gut. :)

**Comment by Fannon** [comment]
Like it :)

2015-02-25 17:50 GMT+01:00 Michael notifications@github.com:
