### ISSUE TITLE
Sommerpause?

### ISSUE THREAD

**Issue by meaku** [web-and-wine/orga#11]
Ich denke wir sollten eine kleine Sommerpause einlegen. 

August würd ich auf jedenfall Pause machen und vielleicht auch noch September. Was meint ihr?

**Comment by MartinKolb1987** [comment]
Denke ich auch. August und September machen wir zu ;-). Wir (Kern-Team) könnten uns aber dennoch treffen und über die Webseite, zukünftige Locations, "die nächsten großen"-Schritte sprechen.

**Comment by meaku** [comment]
Web&Wine Festival!

**Comment by MartinKolb1987** [comment]
Exakt :-D
