### ISSUE TITLE
Sponsor Trinken&Essen

### ISSUE THREAD

**Issue by MartinKolb1987** [web-and-wine/orga#12]
Einfach als Kommentar Firma, Person,... eintragen. Wir freuen uns über jeden Tipp :-)

**Comment by triskweline** [comment]
@MartinKolb1987 makandra kann die Verpflegung für das nächste Meet-Up übernehmen.

Zwei Fragen:
- Kannst du schätzen, wie viele Personen die letzten zwei Meetups gekommen sind?
- Wir können wir die Getränke in der Woche vom 11.11. anliefern? Wir würden unseren Lieferanten dazu beauftragen, der muss aber an einem vorher benannten Tag Zugang zum Lab bekommen.

**Comment by bimpress** [comment]
Klasse!

**Comment by ekkards** [comment]
Ich würde gerne von der Amazon AWS re:invent berichten, läuft gerade jetzt in Las Vegas. Hauptsächlich habe ich Security-Vorträge besucht, aber kann auch von den generellen Trends erzählen, technisch oder business. Was würde euch denn interessieren? Und wie lange?

**Comment by bimpress** [comment]
Klasse,

eher business-like.
Die offline-Präsentation zu  https://aws.amazon.com/de/campaigns/microservices-breakfast/ AWS Microservices Breakfast war schon sehr technisch. 

VG
Robert

Von: ekkards [mailto:notifications@github.com] 
Gesendet: Donnerstag, 8. Oktober 2015 08:19
An: web-and-wine/orga orga@noreply.github.com
Cc: bimpress rb@brunnerrobert.de
Betreff: Re: [orga] Sponsor Trinken&Essen (#12)

Ich würde gerne von der Amazon AWS re:invent berichten, läuft gerade jetzt in Las Vegas. Hauptsächlich habe ich Security-Vorträge besucht, aber kann auch von den generellen Trends erzählen, technisch oder business. Was würde euch denn interessieren? Und wie lange?

**Comment by meaku** [comment]
@bimpress @ekkards: Super Sache! Talk Vorschläge bitte direkt hier rein mit knackigem Titel: https://github.com/web-and-wine/talks/issues. Vom Umfang her haben wir meist so 20 - 30 Minuten.

@henning-koch: Danke! Die letzten Male waren wir immer um die 30. Letztes Mal sogar zeitweise 36. 
 Wegen der Anlieferung könnt ihr euch an kontakt@openlab-augsburg.de wenden.
