### ISSUE TITLE
Sponsoring-Interessenten Jubiläumsausgabe

### ISSUE THREAD

**Issue by MartinKolb1987** [web-and-wine/orga#15]
Einfach einen Kommentar hinterlassen wär tendenziell Interesse hätte :-)
Sobald wir die Rahmenbedingungen kennen melden wir uns.

**Comment by frostney** [comment]
Ich habe Interesse.

**Comment by Robert-F** [comment]
Nachdem wir ja schon "länger" nichts mehr gemacht haben, haben wir auch mal wieder Interesse.

**Comment by meaku** [comment]
:+1:

**Comment by ddanier** [comment]
Wir unterstützen natürlich auch gerne wieder.

**Comment by MartinKolb1987** [comment]
:+1: voll gut!

**Comment by Blacklist** [comment]
Das hört man immer gerne :+1:

**Comment by ekkards** [comment]
auch Interesse, ihr macht es wirklich spannend

**Comment by MartinKolb1987** [comment]
:+1:

**Comment by schacki** [comment]
webspired.de würde sich auch sehr gerne beteiligen.

**Comment by MartinKolb1987** [comment]
:+1:
