### ISSUE TITLE
Vereinsgründung?

### ISSUE THREAD

**Issue by Blacklist** [web-and-wine/orga#19]
Ziel:
- Versicherungen / Haftung
- Aufbau von nötigem finanziellem Puffer
- Speaker, Werbemittel, Events, Bierbänke etc.

Negativ:
- Gründungsaufwand (Notar)
- Vereinsaufwand (Sitzungen, Vereinsrollen, Kontoführung, etc.)

Alternativen zum Pufferaufbau (zusätzlich zu Sponsoren):
- Spendenschwein / -kasse
- Eintrittsschwein (2-5€)

Sollten Leute in die Richtung schon Erfahrungen gesammelt oder andere Vorschläge haben - wir sind über jeden Input extrem dankbar 👍

**Comment by meaku** [comment]
@sbat hat hier Erfahrung soweit ich weiß...

**Comment by MartinKolb1987** [comment]
@meaku stimmt. Allerdings würden wir das gerne umschiffen, da es auf jeden Fall ein Mehraufwand ist... Allerdings möchten wir auch ein bißchen finanziellen Puffer aufbauen (z.B. für Rollups etc.)... und die Gelder auf ein Privatkonto ist nicht ganz so sexy und irgendwie leicht strange :-D

**Comment by sbat** [comment]
Ich habe 2006 den Move-Together e.V. gegründet und mehrere Leute begleitet die einen Verein gegründet haben. Ich würde den Aufwand nicht unterschätzen. Das sind meine Erfahrungen dabei, die sich mit dem @basti auch deken:

## Vorteile
- Nach außen ist es eine unabhängige Organisation.
- Professionelleres Auftreten.
- Bei der Haftung haftet der Vorstand und nicht die Person die Web&Wine angemeldet hat.
- Demokratische Struktur ist Voraussetzung und kann dadurch auch besser gelebt werden.
- ...

## Nachteile
- Ausarbeitung der Satzung.
- Es braucht 7 Gründungsmitglieder die Idealerweise auch aktiv sind.
- Ein Verein muss auch Notariell eingetragen werden.
- Ggf. jährliche/zweijährliche Wahlen, mit Nachtragungen des Vorstandes beim Notar
- Protokolle
- Steuererklärung
- Buchführung
- Tätigkeitsnachweise für das Finanzamt
- Mitgliederverwaltung
- Extra Bankkonto
- Die Kosten für Notar, Steuerberater, ... werden nicht mit de
- Zeitaufwand für die Verwaltung.
- ...

## Fazit
- Da das Web&Wine keine Gewinnerziehlungsabsicht gibt es auch vom Finanzamt ohne Verein keine Bedenken.
- Ich würde es nicht machen, da der Aufwand sehr hoch ist und es zusätzliche Kosten entstehen die mit einem Sparschwein dann nicht mehr tragbar sind.
- Wahrscheinlich wollt ihr euch eh lieber mit den Events auseinandersetzen als mit irgendwelchen Orga-Tasks.
- Die zeitlichen Aufwendungen für die Orgatasks können meiner Ansicht nur ehrenamtlich getragen werden.

## Alternativvorschlag
- Peerigon tritt als Co-Veranstalter auf. So können wir die Veranstaltung über die Haftpflichtversicherung von Peerigon laufen lassen. Das macht bei uns das Kraut nicht fett, da wir schon eine Versicherung haben.
- Die Sponsoren von Web&Wine können auch mal: Speaker, Werbemittel, Events, Bierbänke etc. sponsoren.

**Comment by MartinKolb1987** [comment]
Danke für deinen Input @sbat ! Werden wir in der Sommerpause nochmal genauer bereden.

**Comment by sbat** [comment]
👍
