### ISSUE TITLE
Stream via Periscope

### ISSUE THREAD

**Issue by meaku** [web-and-wine/orga#21]
Sollen wir das mal probieren? Bräuchten dafür wohl ein ordentliches Mic. @greenchapter hast du damit Erfahrung?

**Comment by greenchapter** [comment]
Ich fände es ja super, weil es ja auf den letzten Veranstaltungen immer wieder zu einer Warteliste kam. Ich selber habe damit leider keine Erfahrung, allerdings fände ich es trotzdem ganz gut wenn da gestreamt wird.

Der Slawa hatte da ja auch mal mitgefilmt und vielleicht kann man das ja von da gleich direkt streamen über https://obsproject.com/

Alles in allem würde das halt sicherlich die Reichweite steigern.

**Comment by MartinKolb1987** [comment]
Wir freuen uns über jeden Input und jede aktive Mithilfe. Falls du dich @greenchapter dem Thema und die entsprechende Umsetzung annehmen möchtest, sehr gerne!

**Comment by greenchapter** [comment]
Ja ich würde mich da auch beteiligen, ich habe das auch nicht ohne eigennutzen angebracht, das Problem ist allerdings das ich nicht mehr in Augsburg wohne und deshalb auch ausfalle für eine Umsetzung.
Anschauen würde ich es natürlich 😉

**Comment by meaku** [comment]
Weißt du was man dazu braucht? Vermutlich ein externes Micro und eine ordentliche Kamera. Dann hat man wiederum das Problem mit den Slides die ja auch irgendwo erscheinen sollten (Prio 2). 

Vielleicht können wir uns ja mal zusammensetzen und uns da was ordentliches überlegen. Wichtig ist für uns: 

- geringer Setup Aufwand 
- jemand der das Thema übernimmt 

Unsere Erfahrung mit Videos ist bisher v.a. dass es sehr aufwendig ist. Ob wir das Video dann per Periscope streamen oder später hochladen spielt dabei vom Aufwand her keine Rolle, oder? 

Einfach nur mit dem Smartphone draufzuhalten und zu streamen macht vermutlich keinen glücklich.
