### ISSUE TITLE
Web & Wine Slack?

### ISSUE THREAD

**Issue by pichfl** [web-and-wine/orga#23]
Ich meine letztens vernommen zu haben, dass ein Slack für Web & Wine geplant ist, stimmt das? Wenn ja, wie und wo kann man sich anmelden?

**Comment by MartinKolb1987** [comment]
@pichfl @meaku @Blacklist , korrekt. Wir versuchen es zeitnah über den W&W-Meetup-Verteiler zu verschicken. > Slack Channel ist dann unter https://webandwine.slack.com erreichbar.
