### ISSUE TITLE
Wanderwein

### ISSUE THREAD

**Issue by meaku** [web-and-wine/orga#3]

**Comment by meaku** [comment]
Der Wanderwein steht bei uns im Büro. Vielleicht können wir den heut vorm Treffen noch bekleben.

**Comment by MartinKolb1987** [comment]
Also es gibt noch keine Aufkleber. Hatte leider noch keine Zeit.

**Comment by meaku** [comment]
Kein Ding. Ich hätt einfach des Logo ausgedruckt.

**Comment by MartinKolb1987** [comment]
Wenn es nice aussieht passt das natürlich auch :-). Werde sowieso ein bißchen früher zu euch kommen.
