### ISSUE TITLE
Planning 2024

### ISSUE THREAD

**Issue by tim-olbrich** [web-and-wine/orga#33]
This issue is used for the annual planning of the possible events with the respective sponsors.

| **Month**   | Jan | Feb | Mar | Apr | May | Jun | Jul | Aug | Sep | Oct | Nov | Dec |
| ------- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **Sponsor** |  Makandra |   Uniqbit  |  meteocontrol  |  Miragon  |    Peerigon   | mischok |   AraCom  |   _No event planned so far_  |   _No event planned so far_  |  tresmo  |   _No event planned so far_  |   _No event planned so far_  |
| **Confirmation** |  ✅  |    ✅    |    ✅   | ✅ |  ✅ |  ✅  |   ✅  |  _-_  |  _-_  | ✅  |   _-_  |   _-_  |
| **Preferred Date** | _-_ | _-_ | 21.03. | 11.04.| 23.05.| _-_ | _-_ | _-_ | _-_ | _-_ | _-_ | _-_ |

**Comment by timidak** [comment]
Added the table to our `README.md` in the repo. So I'm now closing this issue.
