### ISSUE TITLE
Sticker für Wanderwein & generell

### ISSUE THREAD

**Issue by MartinKolb1987** [web-and-wine/orga#6]
Servus. Da ich gehört habe, dass wir ein paar mögliche Flaschen für unseren Wanderwein haben wäre es vielleicht an der Zeit einen Sticker zu bauen/bestellen/... . Ich habe mal ein bißchen recherchiert und bin auf folgenden Anbieter gestoßen. Sieht ganz gut aus.

http://www.aufkleberdrucker24.de/standardaufkleber/kontur-aufkleber.html
http://www.aufkleberdrucker24.de/media/Datenblatt-Aufkleberdruck.pdf 

Form: Freiform (siehe auch Datenblatt)
Haltbarkeit: Ablösbar
Material: Weiß matt (habe ich bei meinen aktuellen auch --> sieht fett aus)
Preis: Im Vergleich zu anderen echt gut! (ab 30,-€ inkl. Versand & MwSt.)
Bewertungen: Absolut positiv​
End-Qualität des Drucks: Laut Aussagen anderer Kunden top

Kennt einer von euch noch einen anderen Anbieter oder hat vielleicht sogar noch eine andere Lösung im Kopf? Feedback bitte!

Wegen den Kosten können wir noch mal skypen.

**Comment by meaku** [comment]
Coole Idee! Also dann einfach Web&Wine Sticker mit unserem Logo?

**Comment by MartinKolb1987** [comment]
Würde ich sagen ja. Sieht denke ich ganz nice aus. Auf dem grauen oder weißem Hintergrund? Größe?

**Comment by meaku** [comment]
Der @flootr schlägt flyeralarm für den druck vor.

**Comment by MartinKolb1987** [comment]
Sind die dann von der Qualität wie http://www.redbubble.com/people/giovybus/works/14513498-nodejs?grid_pos=9&p=sticker ? Also nicht hochglanz und auch ausgestanzt?

**Comment by flootr** [comment]
Ich weiß nicht wie die Qualität der von dir verlinkten Aufkleber ist, daher kann ich keinen Vergleich anstellen. Es gibt aber vielfältigste Auswahlmöglichkeiten was Qualität und Anwendungsmöglichkeiten angeht.

Wegen Stanzformen gibt es bpsw. folgende Möglichkeiten:
http://www.flyeralarm.com/de/shop/configurator/index/id/34/outdoor-aufkleber.html#159=612

Ansonsten die üblichen Formen:
http://www.flyeralarm.com/de/shop/configurator/index/id/34/outdoor-aufkleber.html#

War nur als alternativer Vorschlag gedacht. Kein Muss.

**Comment by meaku** [comment]
Die redbubble Dinger sehen schon echt cool aus.

**Comment by MartinKolb1987** [comment]
Klar. Ich hab das schon als Vorschlag betrachtet ;-) – keine Sorge.

Ich persönlich hätte gerne individuelle Stanzformen – das geht bei flyeralarm leider nicht (außer ich habe etwas übersehen).

Absolut, die redbubble Sticker waren gedanklich mein Auswahlkriterium. Nur wollte ich jetzt keinen eigenen "Verkäufer"-Account etc. anlegen. Oder hat jemand von euch einen Account? Also zum selber Sticker-Layouts hochladen etc.

**Comment by meaku** [comment]
Dann redbubble! Wir haben keinen Account. Leg doch einfach einen für uns an :)

**Comment by MartinKolb1987** [comment]
Ich kümmere mich drum.

**Comment by MartinKolb1987** [comment]
http://www.redbubble.com/people/martinkolb/works/14746247-webandwine?p=sticker 

Hab jetzt mal ein paar für Testzwecke bestellt. Mal schauen wie die aussehen.

**Comment by MartinKolb1987** [comment]
Die Test-Sticker sind da. Die Größe und die Qualität sind wunderbar.
![sticker-web-and-wine](https://cloud.githubusercontent.com/assets/1842716/7753356/35001364-ffe5-11e4-8280-c8597a736d17.png)

**Comment by meaku** [comment]
Ich will sofort einen! Bist du in Augsburg?^^

**Comment by MartinKolb1987** [comment]
Haha :-D  Ich gebe dem Basti morgen welche mit. Ihr solltet euch ja bald wieder zum Essen treffen :-)

**Comment by Blacklist** [comment]
Ansonsten bring ich dir welche vorbei - wohnst ja direkt um die Ecke ;)

**Comment by Fannon** [comment]
Will auch haben :)

2015-05-21 18:50 GMT+02:00 Sebastian Huber notifications@github.com:

**Comment by meaku** [comment]
Wir brauchen unbedingt mehr Sticker. Entweder wir finden dafür auch Sponsoren oder wir finden einen billigeren Produzenten.

**Comment by MartinKolb1987** [comment]
Also ich konnte den Preis redbubble.com noch reduzieren. Pro Stück fallen allerdings noch immer 1,64 € an. Die Quali ist wirklich gut, aber der Preis ist halt abartig ^^. Kennt jemand einen Anbieter (mit Selbsterfahrung) der gestanzt Sticker anbietet (Optik ähnlich Foto oben)? Auch mit gleicher Quali.

**Comment by meaku** [comment]
Wie könnten natürlich mal die Dinger von flyeralarm probieren wie von @flootr vorgeschlagen. 

Cool wäre vielleicht auch: http://hexb.in/sticker.html Aber da bräuchten wir eine andere Form. 

http://devstickers.com/javascript ist wahrscheinlich auch nicht billiger, oder?

**Comment by meaku** [comment]
Ok. devstickers ist nur ne Sammlung..

**Comment by MartinKolb1987** [comment]
die hex-Teile sind ja lässig. http://www.aufkleberdrucker24.de/standardaufkleber/kontur-aufkleber.html (siehe gaaaanz oben) wäre auch eine Möglichkeit --> 1000 Stück ~30,- € .

**Comment by MartinKolb1987** [comment]
ich denke das wäre okay...

**Comment by MartinKolb1987** [comment]
ich kümmer mich bei Gelegenheit drum. Okay?

**Comment by meaku** [comment]
Jup. Peerigon zahlt die Sticker! Meld dich nur vorm bestellen, damit peerigon auf der Rechnung steht.

**Comment by MartinKolb1987** [comment]
Sehr nice! Kriegen wir hin.

**Comment by Blacklist** [comment]
Super Sache! :D
