### ISSUE TITLE
Talks sammeln

### ISSUE THREAD

**Issue by meaku** [web-and-wine/orga#8]
Der Vorschlag war ja die Talks in einer Readme zu sammeln. Dann direkt im talks Repo oder? 
Und vielleicht kann man das gerenderte Markdown auch auf der Website einbinden.

**Comment by meaku** [comment]
Also mit "Talks sammeln" mein ich die Slides.

**Comment by MartinKolb1987** [comment]
Jap. Ich finde es gut wenn wir es einfach als Link-Liste in der Readme-"Talks" sammeln. Ich hänge die Links der letzten Meetup-Talks ein.

Die Einbindung wäre auch eine feine Sache. Das können wir dann machen sobald wir eine neue Webseite haben :-)

**Comment by meaku** [comment]
Merci! Vielleicht wird ja aus der neuen Website unser erster Hackathon.

**Comment by MartinKolb1987** [comment]
Klar, kein Thema. Exakt. :-)

**Comment by meaku** [comment]
Das mit dem Talk sammeln läuft soweit. Ich versuch einfach die Talk issues erst zu schließen, wenn die Speaker ihre Talks gemerged haben. Aber vielleicht können wir noch eine Speakers.md machen in der wir zusammenschreiben, was man als Speaker beachten sollte (ohne zu sehr rumzuspießen).

**Comment by MartinKolb1987** [comment]
Ich würde es vielleicht in die Talks-Readme als Info-Block (oben) einbauen. Da man darüber ja dann auch die Issues erstellt. Sonst verwirrt es vielleicht "Talks und Speaker oder Speaker und Talks oder wo muss ich jetzt noch mal reinschauen".
