### ISSUE TITLE
Pecha Kucha Vorträge - 20 Folien x 20 Sekunden

### ISSUE THREAD

**Issue by tobemedia** [web-and-wine/orga#9]
Vorschlag für eines der nächsten Meetups. Es werden mehrere, dafür kurze Vorträge gehalten. Die Idee ist dass eine Präsentation maximal 20 Folien haben darf und je Slide 20 Sekunden Präsentationszeit zur Verfügung stehen. Ein Vortrag dauert somit nur 6:40. Vorteil ist, dass an einem Abend viele verschiedene Vorträge gehalten werden können und es garantiert nicht langweilig wird.

Zur Auflockerung könnte ich mir Vorstellen dass auch Vorträge dabei sind die nicht direkt oder gar nichts mit Web Themen zu tun haben.

see: https://de.wikipedia.org/wiki/Pecha_Kucha

**Comment by MartinKolb1987** [comment]
Finde ich spannend. Allerdings würde ich es nur als Möglichkeit und nicht als Pflicht kommunizieren. Manche Themen brauchen auch mehr Zeit und diese sollten wir dem Redner/der Rednerin auch einräumen. Maximal sollte jeder Vortrag sowieso nur 20 Min. dauern. Ein Versuch ist es aber auf jeden Fall wert. Danke für deine Idee! :-)

Achja, du kannst gerne auch einen Talk (egal ob brachennah oder -fremd) für das nächste Web&Wine einreichen. Wir würden uns freuen :-).

**Comment by meaku** [comment]
Wäre tatsächlich mal spannend. Vielleicht passt das aber auch zusammen mit #10 (feste Struktur für Vorträge). Man könnte aber auch mal so einen Pecha Kucha == Lightning Talk? Abend machen.

**Comment by meaku** [comment]
@tobemedia ich find die Idee gut. Bisher hatten wir noch keine Lightning Talks. Vielleicht können wir mal im Dezember eine Pecha Kucha Action starten.
